image: linagora/node-test-base:8

stages:
  - test
  - swagger
  - deploy-swagger
  - deploy_dev
  
test:
  stage: test
  tags:
    - docker
  services:
    - mongo:3.4
    - elasticsearch:2.4
    - redis:3
    - rabbitmq:3.6
  script:
   - npm i
   - bower i --allow-root
   - grunt

swagger:
  stage: swagger
  tags:
    - master
    - shell
  script:
   - npm i
   - npm prune
   - grunt swagger-generate
  artifacts:
    paths:
     - ./doc/REST_API/swagger/swagger.json

deploy-swagger:
  stage: deploy-swagger
  tags:
    - deployment
    - api.open-paas.org
    - shell
  environment:
    name: api
    url: https://api.open-paas.org
  only:
    - master
  script:
    - perl -i -pe's/"host":"localhost:8080"/"schemes":["https"],"host":"demo.open-paas.org"/' ./doc/REST_API/swagger/swagger.json
    - cp ./doc/REST_API/swagger/swagger.json /var/www/html

deploy_dev:
  stage: deploy_dev
  tags:
    - dev.open-paas.org
    - deployment
  variables:
    GIT_STRATEGY: none
  environment:
    name: dev
    url: https://dev.open-paas.org
  only:
    - master
  script:
    - cd /srv/${CI_PROJECT_NAME}
    - git fetch --all
    - git checkout ${CI_COMMIT_SHA}
    - npm install --ignore-scripts --production
    - npm update --production
    - npm prune
    - bower install --production
    - bower prune
    - git checkout -- .
    - sudo /etc/init.d/rse.dev restart
